services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.next
    restart: always
    ports:
      - "13363:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://158.108.207.232:23363"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.nest
    restart: always
    ports:
      - "23363:3000"
    environment:
      DB_HOST: "158.108.207.232"
      DB_PORT: "3306"
      DB_USER: "dw_student"
      DB_PASS: "dw_student"
      DB_NAME: "DW-student"
      DB_SYNC: "false"
      PORT: "3000"
      API_PREFIX: "api"
